<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GraniteEdgeAI.ModelHardwareCompatibility.Tests" />
    <InternalsVisibleTo Include="GraniteEdgeAI.OpenVino.Tests" />
    <InternalsVisibleTo Include="GraniteEdgeAI.OpenVino.WorkerProcess.Tests" />
  </ItemGroup>

</Project>
