using Microsoft.UI.Input;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media;
using System.Collections.Generic;

namespace GraniteEdgeAI.Features.ModelImport
{
    /// <summary>
    /// Manages the interaction behaviour of the model-preference slider.
    /// </summary>
    public sealed class ModelPreferenceSlider : Slider
    {
        /*
            TEMPORARY CURSOR:

            WinUI does not provide a built-in open-palm or grab cursor.
            The built-in Hand cursor is being used temporarily.

            This will later be replaced with an original OpenPalm.cur
            project asset loaded as a custom Windows cursor.
        */
        private static readonly InputCursor InteractionCursor =
            InputSystemCursor.Create(InputSystemCursorShape.Hand);

        // Stores the Thumb controls generated by the Slider template.
        private readonly List<Thumb> _templateThumbs = new();

        // Records whether the pointer is currently above the slider thumb.
        private bool _isPointerOverThumb;

        // Records whether the user is currently dragging the slider thumb.
        private bool _isDragging;

        /// <summary>
        /// Runs whenever WinUI creates or recreates the Slider template.
        /// </summary>
        protected override void OnApplyTemplate()
        {
            // Removes handlers belonging to any previous template.
            RemoveThumbHandlers();

            // Allows WinUI to create the normal Slider template.
            base.OnApplyTemplate();

            // Finds the draggable Thumb inside the generated template.
            FindThumbs(this, _templateThumbs);

            // Adds pointer and drag behaviour to every Thumb found.
            foreach (Thumb thumb in _templateThumbs)
            {
                thumb.PointerEntered += Thumb_PointerEntered;
                thumb.PointerExited += Thumb_PointerExited;
                thumb.PointerCaptureLost += Thumb_PointerCaptureLost;
                thumb.DragStarted += Thumb_DragStarted;
                thumb.DragCompleted += Thumb_DragCompleted;
            }
        }

        // Records that the pointer has moved over the thumb.
        private void Thumb_PointerEntered(
            object sender,
            PointerRoutedEventArgs e)
        {
            _isPointerOverThumb = true;
            UpdateCursor();
        }

        /*
            Records that the pointer has left the thumb.

            UpdateCursor keeps the interaction cursor visible if dragging
            is still taking place. This prevents cursor flickering.
        */
        private void Thumb_PointerExited(
            object sender,
            PointerRoutedEventArgs e)
        {
            _isPointerOverThumb = false;
            UpdateCursor();
        }

        // Keeps the interaction cursor active for the complete drag operation.
        private void Thumb_DragStarted(
            object sender,
            DragStartedEventArgs e)
        {
            _isDragging = true;
            UpdateCursor();
        }

        // Ends the dragging state and restores the appropriate cursor.
        private void Thumb_DragCompleted(
            object sender,
            DragCompletedEventArgs e)
        {
            _isDragging = false;
            UpdateCursor();
        }

        /*
            Handles cases where Windows ends or cancels pointer capture.

            PointerCaptureLost can happen instead of a normal drag completion,
            so this prevents the cursor from becoming stuck.
        */
        private void Thumb_PointerCaptureLost(
            object sender,
            PointerRoutedEventArgs e)
        {
            _isDragging = false;
            UpdateCursor();
        }

        /*
            Keeps the interaction cursor visible whenever either:

            1. The pointer is above the thumb.
            2. The thumb is currently being dragged.

            This prevents the cursor from switching repeatedly during dragging.
        */
        private void UpdateCursor()
        {
            bool shouldShowInteractionCursor =
                _isPointerOverThumb || _isDragging;

            ProtectedCursor = shouldShowInteractionCursor
                ? InteractionCursor
                : null;
        }

        /// <summary>
        /// Recursively searches the generated visual tree for Thumb controls.
        /// </summary>
        private static void FindThumbs(
            DependencyObject parent,
            ICollection<Thumb> thumbs)
        {
            int childCount = VisualTreeHelper.GetChildrenCount(parent);

            for (int index = 0; index < childCount; index++)
            {
                DependencyObject child =
                    VisualTreeHelper.GetChild(parent, index);

                if (child is Thumb thumb)
                {
                    thumbs.Add(thumb);
                }

                FindThumbs(child, thumbs);
            }
        }

        /*
            Prevents duplicate event handlers if WinUI recreates
            the Slider template.
        */
        private void RemoveThumbHandlers()
        {
            foreach (Thumb thumb in _templateThumbs)
            {
                thumb.PointerEntered -= Thumb_PointerEntered;
                thumb.PointerExited -= Thumb_PointerExited;
                thumb.PointerCaptureLost -= Thumb_PointerCaptureLost;
                thumb.DragStarted -= Thumb_DragStarted;
                thumb.DragCompleted -= Thumb_DragCompleted;
            }

            _templateThumbs.Clear();

            // Resets the interaction state for the new template.
            _isPointerOverThumb = false;
            _isDragging = false;
            ProtectedCursor = null;
        }
    }
}